### ISSUE TITLE
Rename project and change license

### ISSUE THREAD

**Issue by Gemorroj** [Gemorroj/ginfo#8]
This is an embedded library and the LGPL license is more appropriate for it.
Also, there have been many changes compared to the original code. It is probably better to designate the library as a separate project.

**Comment by jrgp** [comment]
I personally don't have a problem with Linfo (or a fork) being relicensed as LGPL. I should have made it MIT or BSD to begin with, but at the time all the cool kids were using GPL and that's what I went with.

The problem is I can't speak for all of Linfo's committers/contributors aside from me, as all of them would also have to approve the license change. This is the same problem that other open source projects face when they try to change licenses, afaik.

**Comment by Gemorroj** [comment]
see https://github.com/jrgp/linfo/issues/82

**Comment by Gemorroj** [comment]
license changed to MIT

**Comment by Gemorroj** [comment]
new name of project is `Ginfo`
